name: DemoCD
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!

  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'www.google.com.br'
    needs: build
    steps:
#      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Deploy Dev
        
  deploy-hmg:
    runs-on: ubuntu-latest
    environment:
      name: hmg
      url: 'www.google.com.br'
    needs: deploy-dev
    steps:
#      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Deploy HMG
  
  deploy-prd:
    runs-on: ubuntu-latest
    environment:
      name: prd
      url: 'www.google.com.br'
    needs: deploy-hmg
    steps:
#      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Deploy PRD
